require('dotenv').config();
const express = require('express');
const cors = require('cors');
const swaggerUi = require('swagger-ui-express');

const { initDb } = require('./db/connect');

const app = express();
const port = process.env.PORT || 8080;

app.use(cors());
app.use(express.json());

// Swagger docs UI, generated by swagger.js into swagger-output.json
try {
  const swaggerDocument = require('./swagger-output.json');
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
} catch (err) {
  console.warn(
    'swagger-output.json not found yet. Run "npm run swagger" to generate it.'
  );
}

app.use('/', require('./routes/index'));

// Basic 404 + error handlers
app.use((req, res) => {
  res.status(404).json({ error: 'Route not found.' });
});
app.use((err, req, res, next) => {
  console.error(err);
  res.status(500).json({ error: 'Something went wrong.' });
});

initDb()
  .then(() => {
    app.listen(port, () => {
      console.log(`Server running on port ${port}`);
      console.log(`Swagger docs available at /api-docs`);
    });
  })
  .catch((err) => {
    console.error('Failed to connect to MongoDB:', err);
    process.exit(1);
  });
